BOT_NAME = 'text_scraper'
SPIDER_MODULES = ['app.scraper.spiders']
NEWSPIDER_MODULE = 'app.scraper.spiders'
ROBOTSTXT_OBEY = True
TELNETCONSOLE_ENABLED = False
USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
DOWNLOAD_DELAY = 1
CONCURRENT_REQUESTS_PER_DOMAIN = 8
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1
AUTOTHROTTLE_MAX_DELAY = 60
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0

ITEM_PIPELINES = {
   'app.scraper.pipelines.DatabasePipeline': 300,
}
